services:
  verticalslice:
    profiles: ["prod"]
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vsa-api
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__Connection=Data Source=/data/VS.db
      - Redis__Configuration=redis:6379
    ports:
      - "5000:8080"
    volumes:
      - ./VS.db:/data/VS.db
    depends_on:
      redis:
        condition: service_healthy

  verticalslice-dev:
    profiles: ["dev"]
    build:
      context: .
      dockerfile: Dockerfile
      target: build  
    container_name: vsa-api-dev
    working_dir: /src
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__Connection=Data Source=/data/VS.db
      - Redis__Configuration=redis:6379
    ports:
      - "5000:5000"
    volumes:
      - ./:/src:delegated 
      - ./VS.db:/data/VS.db
    command: >
      sh -c "
        dotnet watch --no-hot-reload --project /src/VerticalSliceArchitecture.csproj run
      "
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    container_name: vsa-redis
    ports:
      - "6379:6379"
    command: ["redis-server","--appendonly","yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5